name: vulkan_backend
description: Vulkan backend for the Reality Core project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  ffi: ^1.1.1
  pedantic: ^1.0.0
  test: ^1.19.0
  vulkan: 
    git: https://github.com/Intro-Ventors/dart-vulkan